FROM debian:stable-slim

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /app

COPY ./bin/order /app

WORKDIR /app

EXPOSE 8080

CMD ["/app/order"]
