FROM debian:stable-slim

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /app

COPY ./bin/discovery /app

WORKDIR /app

CMD ["/app/discovery"]